services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse
    restart: always
    volumes:
      - ./synapse-data:/data
    networks:
      - matrix-net
  synapse-admin:
    image: awesometechnologies/synapse-admin:latest
    container_name: synapse-admin
    restart: always
    networks:
      - matrix-net
    depends_on:
      - synapse
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_config:/config
      - ./caddy_data:/data
    networks:
      - matrix-net
    ports:
      - "8888:80"
      - "8889:443"
    depends_on:
      - synapse
networks:
  matrix-net:
    driver: bridge
